<?php

namespace NextDeveloper\Stay\Http\Requests\HotelSupplements;

use NextDeveloper\Commons\Http\Requests\AbstractFormRequest;

class HotelSupplementsCreateRequest extends AbstractFormRequest
{

    /**
     * @return array
     */
    public function rules()
    {
        return [
            'stay_hotel_supplement_type_id' => 'nullable|exists:stay_hotel_supplement_types,uuid|uuid',
        'start_date' => 'required|date',
        'end_date' => 'required|date',
        'is_active' => 'required|boolean',
        'is_searcher' => 'required|boolean',
        'is_total' => 'required|boolean',
        'is_on_request' => 'required|boolean',
        'quantity' => 'required',
        'is_percentage' => 'required|boolean',
        'value' => 'nullable|string',
        'information' => 'nullable|string',
        'show_in_bonus' => 'required|boolean',
        'apply_entry_day' => 'required|boolean',
        'stay_provider_id' => 'nullable|exists:stay_providers,uuid|uuid',
        'stay_product_group_id' => 'nullable|exists:stay_product_groups,uuid|uuid',
        'stay_sale_contract_id' => 'nullable|exists:stay_sale_contracts,uuid|uuid',
        'price_guarantee' => 'required|integer',
        'cost_price_guarantee' => 'required|integer',
        'stay_rate_id' => 'nullable|exists:stay_rates,uuid|uuid',
        'payment_date' => 'nullable|date',
        'payment_percentage' => 'nullable',
        'is_early_booking' => 'required|boolean',
        'price_type' => 'required',
        'is_discount' => 'required|boolean',
        'creation_date' => 'nullable|date',
        'collection_date' => 'nullable|date',
        'is_direct_payment' => 'required|boolean',
        'stay_hotel_supplement_class_id' => 'nullable|exists:stay_hotel_supplement_classes,uuid|uuid',
        'parent_stay_hotel_supplement_id' => 'nullable|exists:parent_stay_hotel_supplements,uuid|uuid',
        'is_associated_contract' => 'nullable|boolean',
        'promo_text' => 'nullable|string',
        'base_regime_id' => 'nullable|exists:base_regimes,uuid|uuid',
        'base_room_type_id' => 'nullable|exists:base_room_types,uuid|uuid',
        'stay_offer_supplement_type_id' => 'nullable|exists:stay_offer_supplement_types,uuid|uuid',
        'has_associated_quota' => 'required|boolean',
        'is_special_regime' => 'required|boolean',
        'reservation_start_date' => 'nullable|date',
        'reservation_end_date' => 'nullable|date',
        'is_migrated' => 'required|boolean',
        'is_by_season' => 'required|boolean',
        'season_quote' => 'required',
        'currency' => 'nullable',
        'shift_days' => 'required|integer',
        'show_in_voucher' => 'required|boolean',
        'created_by_hotel' => 'nullable|boolean',
        'is_sent' => 'nullable|boolean',
        'is_rate' => 'required|boolean',
        'fixed_payment_amount' => 'nullable',
        'fixed_sale_payment_amount' => 'nullable',
        'is_promo_text_mandatory' => 'required|boolean',
        'round_sale' => 'required|boolean',
        'is_version_disabled' => 'required|boolean',
        'is_versionable' => 'nullable|boolean',
        'included_extranet_contracts' => 'required|boolean',
        'is_per_pax' => 'required|boolean',
        'is_early_settled' => 'nullable|boolean',
        'is_historic' => 'nullable|boolean',
        'priority' => 'nullable|integer',
        'adult_export_code' => 'nullable',
        'child_export_code' => 'nullable',
        'is_migrated_information' => 'required|boolean',
        'base_supplement_type_id' => 'nullable|exists:base_supplement_types,uuid|uuid',
        'is_extranet' => 'required|boolean',
        'apply_special_markup' => 'required|boolean',
        'is_packaged' => 'required|boolean',
        'supplement_application' => 'required',
        'supplement_type' => 'nullable',
        'is_mandatory' => 'required|boolean',
        'is_fair_rate' => 'required|boolean',
        'is_whole_stay' => 'required|boolean',
        'is_not_whole_stay' => 'required|boolean',
        'duration_applies_to_reservation' => 'required|boolean',
        'apply_default_additionals' => 'required|boolean',
        'apply_default_children' => 'required|boolean',
        'entry_weekdays' => 'nullable',
        'apply_exit_weekdays' => 'required|boolean',
        'apply_weekdays' => 'nullable',
        'min_reservation_days' => 'nullable|integer',
        'max_reservation_days' => 'nullable|integer',
        'min_advance_days' => 'nullable|integer',
        'max_advance_days' => 'nullable|integer',
        'generic_type' => 'nullable',
        'has_baby_occupancy' => 'required|boolean',
        'child_range_from_a' => 'nullable|integer',
        'child_range_to_a' => 'nullable|integer',
        'child_range_to_b' => 'nullable|integer',
        'free_additional1' => 'required|boolean',
        'free_additional2' => 'required|boolean',
        'free_additional_more' => 'required|boolean',
        'free_child_a1' => 'required|boolean',
        'free_child_a2' => 'required|boolean',
        'free_child_a_more' => 'required|boolean',
        'free_child_b1' => 'required|boolean',
        'free_child_b2' => 'required|boolean',
        'free_child_b_more' => 'required|boolean',
        'regime_change_from_id' => 'nullable|exists:regime_change_froms,uuid|uuid',
        'regime_change_to_id' => 'nullable|exists:regime_change_tos,uuid|uuid',
        'room_upgrade_from_id' => 'nullable|exists:room_upgrade_froms,uuid|uuid',
        'room_upgrade_to_id' => 'nullable|exists:room_upgrade_tos,uuid|uuid',
        'free_nights_per_each' => 'nullable|integer',
        'free_nights_number' => 'nullable|integer',
        'free_nights_type' => 'nullable',
        'free_nights_only_once' => 'required|boolean',
        'is_non_refundable' => 'required|boolean',
        'minimum_age' => 'nullable|integer',
        'has_shifted_dates' => 'required|boolean',
        'is_whole_stay_price' => 'required|boolean',
        'price_types' => 'required',
        'applies_only_stay_duration' => 'required|boolean',
        'service_duration' => 'nullable|integer',
        'min_pax' => 'nullable|integer',
        'max_pax' => 'nullable|integer',
        'provider_commission' => 'nullable',
        'client_commissionable' => 'required',
        'multiple_stay_days' => 'nullable|integer',
        'access_control_group' => 'required|integer',
        'resident_application' => 'required|integer',
        'external_code' => 'nullable',
        'external_id' => 'required|string|exists:externals,uuid|uuid',
        ];
    }
    // EDIT AFTER HERE - WARNING: ABOVE THIS LINE MAY BE REGENERATED AND YOU MAY LOSE CODE
}